doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
    orm:
        auto_generate_proxy_classes: true
        auto_mapping: false
        mappings:
            Tournament:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/TournamentManagement/Infrastructure/Mapping'
                prefix: 'App\TournamentManagement\Domain\Entity'
                alias: Tournament
