twig:
    default_path: '%kernel.project_dir%/src/TournamentManagement/Infrastructure/Presentation/Resources/templates'
    paths:
        '%kernel.project_dir%/src/TournamentManagement/Infrastructure/Presentation/Resources/templates': TournamentManagement
when@test:
    twig:
        strict_variables: true
