version: '3.8'
services:
  application:
    container_name: dog_tournament_php
    build:
      context: ./docker
      dockerfile: Dockerfile
    ports:
      - "9003:8000"
    working_dir: /var/www
    command: "symfony server:start --port=8000 --dir=/var/www"
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - dog-tournament-network

  nginx:
    image: nginx:alpine
    container_name: dog_tournament_nginx
    ports:
      - "8083:80"
      - "446:443"
    volumes:
      - ./:/var/www/
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./docker/nginx/ssl/:/etc/ssl
    networks:
      - dog-tournament-network

  database:
    image: postgres:13-alpine
    container_name: dog_tournament_database
    environment:
      POSTGRES_DB: app
      POSTGRES_PASSWORD: ChangeMe
      POSTGRES_USER: symfony
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    ports:
      - "5432"
    networks:
      - dog-tournament-network

networks:
  dog-tournament-network:
    driver: bridge

volumes:
  db-data:
    driver: local
